### ISSUE TITLE
update

### ISSUE THREAD

**Issue by faheemahmed125** [fabricedesre/b2gdroid#3]
please update the apk!

**Comment by fabricedesre** [comment]
This project has been stopped, so I won't release new versions.
Sorry!

**Comment by faheemahmed125** [comment]
please then why there are rumors that its still in works by community

**Comment by fabricedesre** [comment]
B2G OS is being worked on, transitioning to the community. But not b2gdroid.

**Comment by faheemahmed125** [comment]
i wish it did cuz the developer did a very hard job for that...and its work
could get milli0ons
